### ISSUE TITLE
Problem to export to qgis to epanet 

### ISSUE THREAD

**Issue by mariaknt** [qgisred/QGISRed#105]
Hello
I have a problem when I'm trying to export to epanet .  Indeed, I drew my junctions, pipeline and tanks on QGIS but when I try to export my project on epanet, I have the message "not valid epanet path". I tried everything but couldn't fix the problem

**Comment by fmartine** [comment]
Try to avoid any special characters in the epanet2w.exe path, particularly blanks and accents.  You can also uncheck the option to open directly the .inp file after exporting it.  If the problem is not solved, try to capture a screenshot and attach it.

**Comment by mariaknt** [comment]
Thank you , The problem is solved!
