### ISSUE TITLE
No descarga el archivo dll

### ISSUE THREAD

**Issue by Candres25** [qgisred/QGISRed#109]
Cordial saludo compañeros, tengo un inconveniente al momento de intentar utilizar QGISRED no permite descargar el archivo dll de internet, por tanto no he podido utilizar la herramienta.

gracias.

**Comment by fmartine** [comment]
Hola Candres,

Perdona por el tiempo que ha pasado desde que lanzaste esta incidencia.  No sé si finalmente ha podido resolver el problema. Todos los usuarios de QGISRed, que son muchos, están descargando las .dll sin problemas.  Quizás lo único que puede pasar es que no tengas permisos de administrador para instalar librerías en tú máquina.  

Por favor, hazme saber cuál es tu situación actual. 

Saludos,

**Comment by Candres25** [comment]
Hola, saludos.

Aun no logro trabajar con el aplicativo, si tengo permiso de administrador.

![Captura de pantalla 2023-11-05 221537](https://github.com/qgisred/QGISRed/assets/141684800/3eb6f591-c22d-40ec-a0e8-a38038009bc5)

**Comment by fmartine** [comment]
Hola CAndres,

Para instalar las dependencias de QGISRed, esto es , las dlls, no tiene que haber ninguna versión previa instalada de las mismas.  En tal caso se emiten mensajes de incompatibiildad. 

Para ello haz lo siguiente:
- Desinstala el complemento QGISRed desde QGIS y cierras QGIS.
- Desinstala las dlls desde el menú de Aplicaciones de Configuración de Windows. Verás que hay una aplicación denominada QGISRed con el icono característico. 
- Vuelve a abrir QGIS y repite la instalación del complemento.  Una vez instalado y ya visibles los iconos, al pinchar en cualquiera de ellos te llevará a la instalación de las dependencias.

Ten encuenta que la versión 0.16 de QGISRed solo es compatible con la versión de QGIS hasta la 3.28.  Si tienes una version posterior puedes instalar la 3.28 en paralelo, son compatibles.

Si siguen los problemas, también puedes isntalar directametne las librerias desde la siguiente URL:
https://qgisred.upv.es/files/dependencies/1.0.16.0/QGISRed_Installation.msi

Por último, si los problemas persisten, en el mensaje amarillo hay dos botones que ofrecen más información. Accede a dicha información y nos la remites.

Que vaya todo bien.
Saludos,

**Comment by Candres25** [comment]
Muchas gracias por su apoyo, ya fue solucionado.

Buen día.
