### ISSUE TITLE
Problem when trying to install dependencies.

### ISSUE THREAD

**Issue by EnriqueProgramm** [qgisred/QGISRed#111]
Hello, 
I try to use QgisRed V16 in Qgis 3.22.14. I managed to install the plugin, but when I try to click on any tool it asks me to install some dependencies. I click Ok and the menu pop up over and over. As I read in another post, It is possible to install the dependecies from the executable file from Qgis red, which I found in the website from RedHisp (http://redhisp.webs.upv.es/files/QGISRed/1.0.8.0/Installation_x64_en-US.msi). My problem is that I am not allow to install any program in the computer from my job. XD. It is posible to install the dependencies from a zip file?

Excellent job by the way!

Many thanks.

**Comment by fmartine** [comment]
Try to unload the QGISRed plugin and close QGIS. Then remove any previously installed dependencies from the Windows Applications Manager (look for the QGISRed logo application).  Next open QGIS and install again the QGISRed plugin.  Check that the dependencies are now installed automatically.   In case of any problem, you can get the dependencies installer of version 0.16  from the following link   https://qgisred.upv.es/files/dependencies/1.0.16.0/QGISRed_Installation.msi.

Gracias por tu felicitación

**Comment by EnriqueProgramm** [comment]
Problem solved. I procedeed as you said and now it is working!

**Comment by EnriqueProgramm** [comment]
Problem solved. I procedeed as you said and now it is working!
