### ISSUE TITLE
QGISRed shows error when working with QGIS 3.34

### ISSUE THREAD

**Issue by Phatta-Thapa** [qgisred/QGISRed#128]
QGISRed generated the following error when trying to make a new model or trying to run existing models:

TypeError: QgsLineSymbolLayer.setWidthUnit(): argument 1 has unexpected type 'int'

But with earlier version such as 3.28 it is working fine, no such error.

Does that mean QGISRed is not compatible with the newer version?
Is there any solution for this problem?

Thank you in advance.
Phatta Thapa

**Comment by fmartine** [comment]
Please download the new beta version 0.16.11 following the instructions given in issue #126

**Comment by Phatta-Thapa** [comment]
Thank you @fmartine, that solved the problem.
