### ISSUE TITLE
Automatic diameters

### ISSUE THREAD

**Issue by XxGeekoxX12** [qgisred/QGISRed#141]
Is there a way to import diameters of pipes automatically? If yes, provide me plz with the format of the file and what should it contain, Thank you

**Comment by fmartine** [comment]
In the new beta version 0.16.12 (see #issue 140), there is a new option in the Tools menu called 'Scenario builder'.   The first entry allows for importing and exporting diameters from .csv files.  

Make a first test by exporting the current diameters to a .csv file. Then, open the file with any editor and observe the format of the file, which contains a header line and four items per line: element type, identifier, magnitude and value. For example,

ElemType,IdElem,Magnitude,Value
Pipe,10,Diameter,450
Pipe,11,Diameter,350
......

Change now the diameters you want (you can also remove elements or add new ones).  Finally, Import the new file, and all diameters whose ID is recognized will be modified automatically.

Be sure to use the comma to separate the items and the dot as decimal separator.
