### ISSUE TITLE
Demand has been canceled for isolation

### ISSUE THREAD

**Issue by camillenze** [qgisred/QGISRed#98]
ERRORS:
Epanet Toolkit: Err110 in (RunH)
WARNINGS:
Demand has been canceled for isolation junction 'A134'
Demand has been canceled for isolation junction 'A153'
Demand has been canceled for isolation junction 'A181'

**Comment by Phatta-Thapa** [comment]
When I tried to export to epanet without first having any source (i.e., reservoir) I got the same message. But the issue was solved after having the reservoir. May be your section does not have any source.

**Comment by camillenze** [comment]
Hello.
I solved the issue.

The software cancel demand for all node that are not connect to the
network.
I when I fix that problem, every thing is OK.
Thanks very much.

Le dim. 9 avr. 2023 à 02:53, Phatta-Thapa ***@***.***> a
écrit :

**Comment by fmartine** [comment]
Indeed, QGISRed detects network nodes with assigned demand but which are isolated from any supply source or reservoir. In such a case, when exporting the model to EPANET these demands are automatically cancelled to avoid errors when running the model.
